services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017
    volumes:
      - /Users/anercan/Documents/mongodb/database:/data/db
    networks:
      - mongodb_network
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    volumes:
      - /Users/anercan/Documents/mongodb/database:/data/db
    networks:
      - mongodb_network
networks:
  mongodb_network:
    name: mongodb_network
